; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Serial monitor (USB debug)
monitor_speed = 115200
build_flags =
                -DARDUINO_USB_CDC_ON_BOOT=1
                -DARDUINO_USB_MODE=1
                -DENABLE_WEBSOCKETS=0
                -DENABLE_UNO_UART=0
lib_deps =
	olikraus/U8g2
	links2004/WebSockets @ ^2

; [env:esp32-c3-devkitm-1-no-ws]
; platform = espressif32
; board = esp32-c3-devkitm-1
; framework = arduino

; monitor_speed = 115200
; build_flags =
;                 -DARDUINO_USB_CDC_ON_BOOT=1
;                 -DARDUINO_USB_MODE=1
;                 -DENABLE_WEBSOCKETS=0

; lib_deps =
; 	; M3: OLED
;     adafruit/Adafruit SSD1306 @ ^2.5.9
;     adafruit/Adafruit GFX Library @ ^1.11.9
